<?php
/**
 * Migration: Seed Ekadashi Descriptions
 *
 * Adds history, significance, and benefits to all 24 Ekadashi causes.
 */

require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/donation-helpers.php';

$db = getDB();
echo "=== Seeding Ekadashi Descriptions ===\n\n";

$ekadashis = [
    50 => [ // saphala
        'slug' => 'saphala',
        'history' => 'Saphala Ekadashi falls during the Krishna Paksha of the Pausha month (December-January). The name "Saphala" means "fruitful" or "successful." This Ekadashi is described in the Padma Purana, where Lord Krishna narrates its glories to Yudhishthira Maharaja. The story involves King Mahishmati, whose son was cursed by a brahmana to become a demon. The prince lived in a forest, surviving on fruits and roots, and observed this Ekadashi with great devotion. His sincere observance broke the curse, and he regained his human form and kingdom.',
        'significance' => 'Saphala Ekadashi is known for granting the fulfillment of desires and making life truly fruitful. Observing this fast purifies the heart and mind, removing obstacles that prevent spiritual progress. The Padma Purana states that even simple observance of this Ekadashi brings results equal to worshipping the Lord with a thousand sacrifices. It is especially powerful for those seeking success in their endeavors and relief from material difficulties.',
        'benefits' => 'Devotees who observe Saphala Ekadashi with sincerity receive the blessings of Lord Vishnu for success in all undertakings. The fast destroys sins accumulated over many lifetimes and grants material prosperity alongside spiritual advancement. Those who donate food and charity on this day receive manifold returns. The observer is freed from the reactions of sinful activities and progresses toward liberation. Families observe this Ekadashi for overall well-being and harmony.',
    ],
    51 => [ // putrada
        'slug' => 'putrada',
        'history' => 'Pausha Putrada Ekadashi falls during the Krishna Paksha of the Pausha month (December-January). The name means "bestower of sons." This Ekadashi is described in the Brahma Vaivarta Purana, where Lord Krishna explains to Yudhishthira Maharaja the story of a king named Sumedha who had no children despite being righteous. His wife observed this Ekadashi with great devotion and prayed for a child. Pleased by her sincerity, the Lord blessed them with a glorious son who became a great king.',
        'significance' => 'Putrada Ekadashi holds special significance for those desiring children and for the welfare of existing children. In Vedic culture, having children — especially devoted sons — is considered one of the most important responsibilities of grihastha life. This Ekadashi is observed to invoke the blessings of Lord Vishnu for progeny and for the protection and well-being of children. It also signifies the importance of raising children in spiritual consciousness.',
        'benefits' => 'Observing Putrada Ekadashi blesses childless couples with the boon of children. For those who already have children, it ensures their health, wisdom, and spiritual progress. The fast purifies the consciousness of the parents, enabling them to raise their children in a spiritually conducive environment. Donations made on this day — especially to educational institutions and temples — bring lasting merit. The observer is blessed with family happiness and the joy of raising devoted children.',
    ],
    52 => [ // sattila
        'slug' => 'sattila',
        'history' => 'Sat-tila Ekadashi falls during the Krishna Paksha of the Magha month (January-February). The name "Sat-tila" refers to the seven types of sesame (tila) used in the observance. This Ekadashi is described in the Padma Purana, where Lord Krishna tells Yudhishthira about a brahmani (brahmana\'s wife) who was very devoted but poor. She observed this Ekadashi by bathing in sesame water, offering sesame in fire sacrifices, eating sesame preparations, and donating sesame to brahmanas. Through this sevenfold use of sesame, she purified herself and attained liberation.',
        'significance' => 'Sat-tila Ekadashi emphasizes the spiritual potency of sesame (tila) in Vedic rituals. Sesame is considered highly sacred and is used in Shraddha ceremonies, fire sacrifices, and worship of Lord Vishnu. This Ekadashi teaches that even simple, sattvic offerings made with devotion are more pleasing to the Lord than elaborate rituals performed without sincerity. It is also observed to honor departed ancestors and seek their blessings.',
        'benefits' => 'Observing Sat-tila Ekadashi with the sevenfold use of sesame grants liberation from sinful reactions. The fast purifies the body and mind, removing impurities accumulated through wrongdoings. Donating sesame to brahmanas and temples on this day is considered extremely meritorious and helps in Shraddha karma for ancestors. The observer receives the grace of Lord Vishnu and progress on the spiritual path. It also brings peace to departed family members.',
    ],
    53 => [ // bhaimi
        'slug' => 'bhaimi',
        'history' => 'Bhaimi Ekadashi, also known as Jaya Ekadashi, falls during the Krishna Paksha of the Magha month (January-February). This Ekadashi is described in the Vishnu Purana, where the story of King Harishchandra is narrated. The king had lost his kingdom, wife, and son due to a curse. When his son was about to be cremated, the king remembered this Ekadashi and observed it with devotion. Lord Vishnu appeared and restored everything — his son came back to life, his kingdom was returned, and he regained his glory.',
        'significance' => 'Bhaimi Ekadashi holds the power to reverse misfortunes and restore what has been lost. It is observed during the auspicious Magha month when the influence of spiritual practices is heightened. This Ekadashi teaches that even in the darkest moments of life, sincere devotion to the Lord can turn the tide. It is also associated with overcoming enemies and obstacles, as the name "Jaya" means "victory."',
        'benefits' => 'Devotees who observe Bhaimi Ekadashi receive divine protection from enemies and obstacles. The fast has the power to reverse curses and restore lost fortunes — wealth, health, relationships, and position. Those who donate food, clothes, and sesame on this day receive immense merit. The observer is blessed with victory over all challenges and the grace of Lord Vishnu for a prosperous and peaceful life.',
    ],
    54 => [ // vijaya
        'slug' => 'vijaya',
        'history' => 'Vijaya Ekadashi falls during the Krishna Paksha of the Phalguna month (February-March). The name means "victory." This Ekadashi is described in the Brahma Purana, where Lord Krishna narrates the story of a king named甘蔗 (甘蔗) who was a great devotee but faced many military challenges. On the advice of his spiritual master, he observed this Ekadashi with strict vows. The Lord granted him victory over all enemies, and he ruled his kingdom peacefully for many years.',
        'significance' => 'Vijaya Ekadashi is observed to seek victory in all endeavors — both material and spiritual. In the battlefield of life, devotees face numerous obstacles from internal enemies (lust, anger, greed) and external challenges. This Ekadashi empowers the devotee to overcome both. It falls during the month of Phalguna, which is associated with the divine pastimes of Lord Krishna, making it especially potent for spiritual advancement.',
        'benefits' => 'Observing Vijaya Ekadashi grants victory over all forms of adversity — disease, debt, enemies, and obstacles. The fast destroys sinful reactions and grants the observer courage and determination. Those who donate food and worship the Lord with devotion on this day receive special blessings for success in their endeavors. The observer is freed from fear and anxiety, and their life moves toward prosperity and spiritual fulfillment.',
    ],
    55 => [ // amalaki
        'slug' => 'amalaki',
        'history' => 'Amalaki Ekadashi falls during the Krishna Paksha of the Phalguna month (February-March). The name refers to the Amalaki (Indian gooseberry) tree, which is considered a manifestation of Lord Vishnu. This Ekadashi is described in the Padma Purana, where Lord Krishna explains that worshipping the Amalaki tree on this day is equivalent to worshipping all the demigods. The story involves a king named Chitraratha who was childless. He worshipped the Amalaki tree on this Ekadashi and was blessed with a son who became a great devotee.',
        'significance' => 'Amalaki Ekadashi is observed during the auspicious period leading up to Holi. The Amalaki tree represents the Trimurti — Brahma in the roots, Vishnu in the trunk, and Shiva in the branches. Worshipping this tree on Ekadashi is considered one of the most powerful spiritual practices. It is also observed for good health, as the Amalaki fruit is one of the most healing substances in Ayurveda.',
        'benefits' => 'Observing Amalaki Ekadashi grants relief from all types of diseases and health problems. The fast purifies the blood, strengthens the immune system, and brings overall physical well-being. Donating Amalaki fruits and food to brahmanas on this day brings immense merit. The observer receives the blessings of Lord Vishnu for good health, prosperity, and spiritual progress. It is especially beneficial for those suffering from chronic illnesses.',
    ],
    56 => [ // papamocani
        'slug' => 'papamocani',
        'history' => 'Papamochani Ekadashi falls during the Krishna Paksha of the Chaitra month (March-April). The name means "destroyer of sins." This Ekadashi is described in the Brahma Purana, where the story of King Kalmashapada is narrated. The king was cursed by a brahmana to become a man-eating demon. He wandered in the forest, eating human flesh for years. When the curse was about to end, he observed this Ekadashi with great devotion. The Lord freed him from the demoniac form, purified him of all sins, and restored his kingdom.',
        'significance' => 'Papamochani Ekadashi falls during the Chaitra month, which marks the beginning of the Hindu New Year. Observing this Ekadashi at the start of the year ensures freedom from sins throughout the year. The name literally means "the liberator from sins," and the scriptures describe it as having extraordinary power to cleanse even the most severe sinful reactions. It is observed for spiritual purification and a fresh start.',
        'benefits' => 'The primary benefit of Papamochani Ekadashi is complete liberation from all sinful reactions — past, present, and future. The fast destroys sins that other austerities cannot remove. Those who observe this Ekadashi and donate food, gold, and cows on this day receive immense spiritual merit. The observer\'s consciousness is purified, enabling them to engage in devotional service more effectively. It brings peace of mind and freedom from guilt and anxiety.',
    ],
    57 => [ // kamada
        'slug' => 'kamada',
        'history' => 'Kamada Ekadashi falls during the Shukla Paksha of the Chaitra month (March-April). The name means "fulfiller of desires." This Ekadashi is described in the Padma Purana, where Lord Krishna narrates the story of a Gandharva (celestial musician) named Pundarika who was cursed by a sage to become a demon for ignoring the sage during a concert. Desperate to break the curse, Pundarika\'s wife advised him to observe this Ekadashi. He observed it with great devotion, and the Lord freed him from the curse, restoring his celestial form.',
        'significance' => 'Kamada Ekadashi falls on the first Ekadashi after Holi, during the Chaitra month. It is observed for the fulfillment of desires — both material and spiritual. The scriptures state that this Ekadashi has the power to fulfill any sincere wish of the devotee. It is especially observed by those seeking to overcome specific problems or achieve particular goals in life. The timing during the spring season adds to its spiritual potency.',
        'benefits' => 'Observing Kamada Ekadashi fulfills the desires of the sincere devotee. The fast removes all obstacles in the path of the observer and grants success in their endeavors. Those who donate food, clothing, and charity on this day receive manifold returns. The observer is blessed with the grace of Lord Vishnu, who removes all difficulties and grants prosperity. It is especially beneficial for those facing legal issues, relationship problems, or career challenges.',
    ],
    58 => [ // varuthini
        'slug' => 'varuthini',
        'history' => 'Varuthini Ekadashi falls during the Krishna Paksha of the Kartika month (October-November). The name means "protected" or "shielded." This Ekadashi is described in the Brahma Vaivarta Purana, where Lord Krishna tells Yudhishthira about a king named Mandhata who was a great devotee but faced constant attacks from his enemies. He observed this Ekadashi with strict vows and prayed for protection. The Lord appeared and blessed him with invincibility and divine protection, and his enemies were vanquished.',
        'significance' => 'Varuthini Ekadashi falls during the sacred Kartika month, when devotional practices are especially powerful. The name signifies divine protection — the Lord shields His devotees from all dangers. This Ekadashi is observed for protection from enemies, negative energies, and unforeseen calamities. It is also observed during the period when Lord Vishnu is resting (Chaturmasya), making devotion during this time especially pleasing to the Lord.',
        'benefits' => 'Observing Varuthini Ekadashi grants divine protection from all forms of danger — physical, mental, and spiritual. The fast acts as a spiritual shield, protecting the observer from negative influences and enemies. Those who donate food, warm clothes, and blankets on this day during the cold Kartika month receive immense merit. The observer is blessed with fearlessness, courage, and the Lord\'s protection throughout the year.',
    ],
    59 => [ // mohini
        'slug' => 'mohini',
        'history' => 'Mohini Ekadashi falls during the Krishna Paksha of the Vaishakha month (April-May). The name refers to the Mohini avatar of Lord Vishnu, who appeared as a beautiful enchantress to distribute the nectar of immortality (amrita) to the demigods. This Ekadashi is described in the Padma Purana, where Lord Krishna explains that observing this Ekadashi removes the illusion (maya) that binds the soul in material existence.',
        'significance' => 'Mohini Ekadashi is observed to overcome the powerful illusion of material existence. Just as Lord Vishnu as Mohini distributed amrita to the demigods, this Ekadashi grants the nectar of spiritual life to the sincere observer. It is especially powerful for breaking free from addictions, bad habits, and material attachments. The Vaishakha month is considered highly auspicious for spiritual practices.',
        'benefits' => 'Observing Mohini Ekadashi frees the devotee from the clutches of material illusion (maya). The fast breaks attachments to sinful activities and impure consciousness. Those who observe this Ekadashi with devotion receive the ability to discriminate between right and wrong and make spiritually elevated choices. Donations on this day — especially of food and educational materials — bring lasting merit. The observer is blessed with clarity of mind and progress in spiritual life.',
    ],
    60 => [ // apara
        'slug' => 'apara',
        'history' => 'Apara Ekadashi falls during the Krishna Paksha of the Jyeshtha month (May-June). The name means "unlimited" or "boundless." This Ekadashi is described in the Brahma Purana, where Lord Krishna narrates the story of a king named Kritavirya who was extremely wealthy but had committed many sins through his harsh统治. On the advice of his priests, he observed this Ekadashi with great devotion and donated generously. The Lord forgave his sins and blessed him with liberation.',
        'significance' => 'Apara Ekadashi is observed for the destruction of unlimited sins and the accumulation of unlimited merit. The name itself signifies the boundless results of this observance. It falls during the Jyeshtha month when the summer heat intensifies, symbolizing the burning away of sinful reactions through the fire of devotion. This Ekadashi is especially observed by those who have accumulated heavy sinful reactions.',
        'benefits' => 'Observing Apara Ekadashi destroys sins that are otherwise very difficult to atone for. The fast grants unlimited spiritual merit that accumulates across lifetimes. Those who donate food, water, and cooling drinks during the hot Jyeshtha month receive immense blessings. The observer is freed from the reactions of all types of sinful activities — including those committed knowingly or unknowingly. It brings liberation from the cycle of birth and death.',
    ],
    61 => [ // nirjala
        'slug' => 'nirjala',
        'history' => 'Pandava Nirjala Ekadashi falls during the Shukla Paksha of the Jyeshtha month (May-June). "Nirjala" means "without water." This Ekadashi is described in the Mahabharata, where Bhima — the second Pandava brother — was unable to observe the regular Ekadashis because of his enormous appetite. He requested a single observance that would equal all 24 Ekadashis. Lord Vyasa told him to observe this waterless Ekadashi. Bhima observed it with great difficulty but succeeded, and the Lord blessed him with immense spiritual merit.',
        'significance' => 'Nirjala Ekadashi is considered the most powerful of all Ekadashis. Observing it without even drinking water is said to bestow the merit of observing all 24 Ekadashis of the year. It falls during the hottest month of Jyeshtha, making the waterless fast particularly challenging. This Ekadashi teaches the supreme power of determination and sacrifice in spiritual life. It is observed for the purification of the soul and the destruction of all sins.',
        'benefits' => 'The observer of Nirjala Ekadashi receives the combined merit of all 24 Ekadashis of the year. This single fast destroys all sinful reactions, grants liberation from the cycle of birth and death, and brings the devotee closer to God. Despite the difficulty, those who observe it with faith receive extraordinary spiritual advancement. Donations of water, buttermilk, and food on this day are considered extremely meritorious. The observer is blessed with divine strength and unwavering devotion.',
    ],
    62 => [ // yogini
        'slug' => 'yogini',
        'history' => 'Yogini Ekadashi falls during the Krishna Paksha of the Ashadha month (June-July). This Ekadashi is described in the Brahma Vaivarta Purana, where Lord Krishna tells Yudhishthira about a gardener named Hem who served the demigod Kubera. One day he failed to deliver flowers on time due to a mistake. Kubera cursed him to become a leper. Hem\'s wife advised him to observe Yogini Ekadashi. He observed it with devotion, and the Lord freed him from the curse, restoring his health and position.',
        'significance' => 'Yogini Ekadashi is observed for liberation from diseases, particularly skin ailments and chronic illnesses. The name "Yogini" refers to the spiritual energy (yogini shakti) that resides in the devotee during this observance. It falls during the beginning of Chaturmasya, making it especially potent for spiritual practices. This Ekadashi teaches that even those who have made mistakes can be restored through sincere devotion.',
        'benefits' => 'Observing Yogini Ekadashi cures diseases and grants excellent health. The fast purifies the blood, removes toxins, and strengthens the body\'s natural healing abilities. Those who donate food, medicine, and fruits on this day receive the blessings of Lord Vishnu for good health. The observer is freed from skin diseases, chronic ailments, and the reactions of past sinful activities. It brings physical vitality and spiritual energy.',
    ],
    63 => [ // sayana
        'slug' => 'sayana',
        'history' => 'Sayana Ekadashi, also known as Devshayani Ekadashi, falls during the Krishna Paksha of the Ashadha month (June-July). "Sayana" means "sleeping" — on this day, Lord Vishnu enters His four-month cosmic sleep (Yoga Nidra) on the cosmic ocean (Kshira Sagara). This Ekadashi is described in the Padma Purana, where Lord Krishna explains that no auspicious activities like marriages, house-warming ceremonies, or new ventures should be undertaken during the four months the Lord sleeps. The story of King Yudhishthira\'s question to Lord Krishna about this Ekadashi is narrated in detail.',
        'significance' => 'Sayana Ekadashi marks the beginning of Chaturmasya — the four-month period when Lord Vishnu rests. It is observed with great devotion to seek the Lord\'s blessings before He enters cosmic sleep. All auspicious ceremonies are suspended during this period. This Ekadashi teaches the importance of spiritual discipline and restraint. It is also observed to ensure that the observer is protected during the Chaturmasya period.',
        'benefits' => 'Observing Sayana Ekadashi grants protection during the Chaturmasya period. The fast ensures that the observer\'s spiritual progress continues even while the Lord rests. Those who observe this Ekadashi and donate food, bedding, and clothes receive the Lord\'s special grace. The observer is blessed with the cessation of all sinful reactions and is protected from negative influences during the Chaturmasya months. It brings peace and spiritual stability.',
    ],
    64 => [ // kamika
        'slug' => 'kamika',
        'history' => 'Kamika Ekadashi falls during the Krishna Paksha of the Shravana month (July-August). The name means "desirable" or "wish-fulfilling." This Ekadashi is described in the Padma Purana, where Lord Krishna tells Yudhishthira that worshipping Lord Vishnu with Tulasi leaves on this day destroys all sins. The story involves a brahmana who accidentally killed a brahmana (brahma-hatya). Desperate for atonement, he observed Kamika Ekadashi with Tulasi worship, and the Lord forgave his grave sin.',
        'significance' => 'Kamika Ekadashi falls during the sacred Shravana month when the influence of Lord Vishnu is especially strong. The worship of Tulasi (holy basil) on this day is considered extraordinarily powerful. The Padma Purana states that even looking at Tulasi leaves on this Ekadashi destroys sins. This Ekadashi is observed for the purification of even the most severe sinful reactions, including brahma-hatya (the killing of a brahmana).',
        'benefits' => 'Observing Kamika Ekadashi destroys even the gravest sins, including brahma-hatya. The worship of Tulasi on this day grants liberation from all sinful reactions. Those who donate Tulasi plants, food, and worship Lord Vishnu with Tulasi leaves receive immense spiritual merit. The observer is blessed with purity of consciousness and freedom from the reactions of past wrongdoings. It brings divine grace and progress toward liberation.',
    ],
    65 => [ // pavitropana
        'slug' => 'pavitropana',
        'history' => 'Pavitropana Ekadashi, also known as Pavitra Ekadashi, falls during the Krishna Paksha of the Bhadrapada month (August-September). The name means "making pure." This Ekadashi is described in the Brahma Purana, where Lord Krishna narrates the story of King Kuru who performed great austerities but was affected by the reactions of killing many people in battle. He observed this Ekadashi with strict vows and the Lord purified him completely. The "pavitra" (sacred thread) ceremony is performed on this day in many traditions.',
        'significance' => 'Pavitropana Ekadashi falls near the end of Chaturmasya and is observed for complete purification of body, mind, and soul. The sacred thread ceremony (Pavitropana) performed on this day symbolizes spiritual rebirth. This Ekadashi is observed to cleanse all impurities accumulated during the Chaturmasya period. It marks the spiritual renewal of the devotee and preparation for the festive season ahead.',
        'benefits' => 'Observing Pavitropana Ekadashi purifies the devotee completely — physically, mentally, and spiritually. The fast cleanses all impurities accumulated over time and renews the observer\'s spiritual life. Donations of sacred threads, food, and clothing on this day bring immense merit. The observer is blessed with spiritual renewal, purity of consciousness, and a fresh beginning in their devotional life. It marks the end of Chaturmasya restrictions and the resumption of auspicious activities.',
    ],
    66 => [ // annada
        'slug' => 'annada',
        'history' => 'Annada Ekadashi, also known as Aja Ekadashi, falls during the Krishna Paksha of the Bhadrapada month (August-September). The name "Annada" means "giver of food" and "Aja" means "unborn." This Ekadashi is described in the Skanda Purana, where Lord Krishna explains that this Ekadashi was observed by King Bali to regain his kingdom from Vamana Deva. It is also associated with the origin of the Annakut (mountain of food) offering. The story of a poor brahmani who offered simple food on this day and attained liberation is also narrated.',
        'significance' => 'Annada Ekadashi emphasizes the supreme importance of food charity (anna-dana) in spiritual life. The scriptures state that feeding a hungry person is equal to feeding the Lord Himself. This Ekadashi is observed for the purification of the digestive system and for the merit earned through food distribution. It falls during the Bhadrapada month, which is associated with the Govardhan Puja and the Annakut offering.',
        'benefits' => 'Observing Annada Ekadashi grants the merit of feeding thousands. The fast purifies the digestive fire (agni) and removes diseases related to the stomach and intestines. Those who donate food — especially to the poor, travelers, and brahmanas — on this day receive immense spiritual merit. The observer is blessed with never going hungry and with the ability to provide food for others. It brings the blessings of Lord Vishnu for abundance and generosity.',
    ],
    67 => [ // parivartini
        'slug' => 'parivartini',
        'history' => 'Parshva Ekadashi, also known as Parivartini Ekadashi, falls during the Krishna Paksha of the Bhadrapada month (August-September). "Parivartini" means "changing" — on this day, the Lord shifts from His sleeping position to His left side during cosmic sleep. This Ekadashi is described in the Padma Purana, where Lord Krishna tells Yudhishthira about the significance of the Lord\'s cosmic sleep and His turning point. The story of King Bali and Vamana Deva is also connected to this Ekadashi.',
        'significance' => 'Parivartini Ekadashi marks the halfway point of Chaturmasya — the moment when Lord Vishnu changes His sleeping position. This turning point is observed with special devotion and prayers. The change of position symbolizes the beginning of the Lord\'s awakening process, bringing hope and renewal to devotees. This Ekadashi is observed for spiritual transformation and for seeking the Lord\'s blessings as He begins to stir from cosmic sleep.',
        'benefits' => 'Observing Parivartini Ekadashi brings spiritual transformation and renewal. The fast coincides with the cosmic turning point, making it especially potent for changing one\'s life trajectory. Those who donate food, bedding, and money on this day receive the Lord\'s grace for positive change. The observer is blessed with the courage to make necessary changes in their life and with the Lord\'s guidance during the transition. It brings hope and the promise of spiritual awakening.',
    ],
    68 => [ // indira
        'slug' => 'indira',
        'history' => 'Indira Ekadashi falls during the Krishna Paksha of the Ashvina month (September-October). This Ekadashi is described in the Brahma Purana, where Lord Krishna narrates the story of King Indradyumna who was a great devotee but had inadvertently neglected his spiritual duties. When his son died, he was devastated. The sage Narada advised him to observe Indira Ekadashi for his son\'s liberation. The king observed it with great devotion, and his son was not only liberated but also restored to life.',
        'significance' => 'Indira Ekadashi is observed primarily for the liberation (moksha) of departed ancestors and family members. The name "Indira" is associated with Indra, the king of heaven, signifying the royal and powerful nature of this observance. It falls just before the beginning of the festive season, making it an important time for honoring ancestors. This Ekadashi teaches that the devotion of the living can liberate even those who have passed on.',
        'benefits' => 'Observing Indira Ekadashi liberates departed ancestors from their karmic reactions and grants them a higher birth or liberation. The fast purifies the observer\'s lineage (kula) and removes ancestral curses (pitru dosha). Those who perform Shraddha ceremonies and donate food on this day receive the blessings of their ancestors. The observer is blessed with family harmony, the removal of obstacles, and spiritual progress for both the living and the departed.',
    ],
    69 => [ // papankusa
        'slug' => 'papankusa',
        'history' => 'Papa-ankusha Ekadashi falls during the Krishna Paksha of the Ashvina month (September-October). The name means "the goad that hooks sins" — "papa" means sin and "ankusha" means a goad or hook used to control elephants. This Ekadashi is described in the Padma Purana, where Lord Krishna explains that observing this Ekadashi removes sins as effectively as an ankusha controls a wild elephant. The story involves a hunter named Kritantasena who accidentally killed many animals. He observed this Ekadashi and was freed from all sinful reactions.',
        'significance' => 'Papa-ankusha Ekadashi is observed for the destruction of even the most stubborn sinful habits and reactions. Just as an ankusha controls a wild elephant, this Ekadashi controls and removes the powerful urges of sin. It falls during the Ashvina month when the influence of negative energies is strong, making this observance especially protective. This Ekadashi is observed for overcoming addictions, breaking bad habits, and controlling the mind.',
        'benefits' => 'Observing Papa-ankusha Ekadashi destroys sinful habits and reactions that are otherwise very difficult to overcome. The fast acts as a spiritual goad, directing the mind away from sin and toward devotion. Those who donate food, clothing, and worship the Lord on this day receive the power to control their senses. The observer is blessed with self-discipline, freedom from addictions, and the strength to follow the spiritual path. It brings liberation from the cycle of sin.',
    ],
    70 => [ // rama
        'slug' => 'rama',
        'history' => 'Rama Ekadashi falls during the Krishna Paksha of the Kartika month (October-November). This Ekadashi is described in the Skanda Purana, where Lord Krishna tells Yudhishthira about a wealthy merchant named Dharmadhan who had a prostitute\'s daughter as his wife. When he learned of her unchaste behavior, he was devastated. On the advice of a sage, he observed Rama Ekadashi with strict vows. The Lord purified both him and his wife, and they were reunited in a spiritually purified relationship.',
        'significance' => 'Rama Ekadashi falls during the auspicious Kartika month and is observed for purification of relationships and the restoration of dharma. The name "Rama" refers to Lord Rama, the ideal king and embodiment of dharma. This Ekadashi is observed for overcoming sinful desires, especially those related to illicit relationships, and for cultivating pure, spiritually-based connections. It is also observed for the general welfare of family life.',
        'benefits' => 'Observing Rama Ekadashi purifies relationships and restores harmony in family life. The fast destroys sinful desires and promotes self-control and spiritual discipline. Those who donate food, clothes, and worship Lord Rama on this day receive the blessings for a harmonious family life. The observer is freed from the reactions of illicit sexual activities and is blessed with pure, devotional relationships. It brings peace, harmony, and spiritual progress in family life.',
    ],
    71 => [ // utthana
        'slug' => 'utthana',
        'history' => 'Utthana Ekadashi, also known as Devotthan Ekadashi, falls during the Shukla Paksha of the Kartika month (October-November). "Utthana" means "awakening" — on this day, Lord Vishnu awakens from His four-month cosmic sleep (Yoga Nidra). This Ekadashi is described in the Padma Purana, where Lord Krishna explains the significance of the Lord\'s awakening. The story of King Talasura, who was a demon haunting the cremation grounds, is also associated — he observed this Ekadashi and was freed from his demoniac form.',
        'significance' => 'Utthana Ekadashi marks the end of Chaturmasya — the auspicious moment when Lord Vishnu awakens from cosmic sleep. This awakening signals the resumption of all auspicious ceremonies and activities. It is observed with great joy and celebration across Vaishnava communities. The Kartika month is considered the best month for spiritual practices, and this Ekadashi adds special potency to devotional activities. The Tulasi Vivaha (marriage of Tulasi to Lord Shaligram) is often celebrated around this time.',
        'benefits' => 'Observing Utthana Ekadashi marks a fresh spiritual beginning as the Lord awakens. The fast renews the observer\'s spiritual energy and dedication. Those who celebrate the Lord\'s awakening with devotional activities, feasts, and donations receive immense blessings. The observer is blessed with renewed spiritual vigor, the resumption of auspicious activities, and the Lord\'s attentive grace. It brings joy, celebration, and a fresh start in spiritual life.',
    ],
    72 => [ // utpanna
        'slug' => 'utpanna',
        'history' => 'Utpanna Ekadashi falls during the Krishna Paksha of the Margashirsha month (November-December). "Utpanna" means "born" or "manifested." This Ekadashi is described in the Padma Purana, where Lord Krishna tells Yudhishthira that this Ekadashi was "born" from the body of the Lord during His battle with the demon Mura. When the Lord was resting in a cave, the demon Mura attacked Him. From the Lord\'s sleeping form, this Ekadashi appeared, fought and killed the demon, and protected the Lord. The Lord was pleased and named her "Mura-Nashini" (destroyer of Mura).',
        'significance' => 'Utpanna Ekadashi holds special significance as the "birth" of Ekadashi itself. The scriptures describe that Ekadashi is a powerful devi (goddess) who was manifested from Lord Vishnu\'s divine energy. Observing this Ekadashi is like worshipping the mother of all Ekadashis. It falls during the beginning of the most auspicious month for devotional practices (Margashirsha/Kartika). This Ekadashi is observed for protection from demons (both external and internal — the six enemies of the mind).',
        'benefits' => 'Observing Utpanna Ekadashi grants the special blessings of the Ekadashi devi herself. The fast destroys all forms of demonic influence — both external negative energies and internal enemies (lust, anger, greed, etc.). Those who worship the Lord with Tulasi and food on this day receive powerful protection. The observer is blessed with divine protection, freedom from fear, and the destruction of all obstacles on the spiritual path. It brings the grace of the Ekadashi devi for lifelong protection.',
    ],
    73 => [ // moksada
        'slug' => 'moksada',
        'history' => 'Mokshada Ekadashi falls during the Shukla Paksha of the Margashirsha month (November-December). "Mokshada" means "liberator" or "granting liberation." This Ekadashi is also celebrated as Gita Jayanti — the day Lord Krishna spoke the Bhagavad-gita to Arjuna on the battlefield of Kurukshetra over 5,000 years ago. This Ekadashi is described in the Padma Purana and is also mentioned in the Mahabharata. The story of King Daivavrata, who was devoted to Lord Vishnu and observed this Ekadashi for the liberation of his father from a lower birth, is narrated in the Puranas.',
        'significance' => 'Mokshada Ekadashi is one of the most sacred Ekadashis as it coincides with Gita Jayanti — the advent day of the Bhagavad-gita. The scriptures state that Lord Krishna chose this day to reveal the most confidential spiritual knowledge to Arjuna. Observing this Ekadashi is equivalent to studying the entire Bhagavad-gita. It falls during the Margashirsha month, considered the most auspicious month for worship of Lord Krishna. This Ekadashi is observed for liberation (moksha) and for deepening one\'s understanding of the Gita\'s teachings.',
        'benefits' => 'Observing Mokshada Ekadashi grants liberation (moksha) — the ultimate goal of human life. The fast, combined with the study of the Bhagavad-gita, purifies the consciousness completely. Those who donate food, clothes, and Gita books on this day receive immense spiritual merit. The observer is blessed with deep spiritual understanding, freedom from the cycle of birth and death, and the ability to follow the teachings of the Gita in daily life. It brings the highest spiritual benefit of any Ekadashi observance.',
    ],
];

$updatedCount = 0;
$failedCount = 0;

$stmt = $db->prepare("UPDATE donation_causes SET history = ?, significance = ?, benefits = ? WHERE id = ?");

foreach ($ekadashis as $id => $data) {
    try {
        $stmt->execute([$data['history'], $data['significance'], $data['benefits'], $id]);
        $updatedCount++;
        echo "  [OK] {$data['slug']} (id={$id})\n";
    } catch (PDOException $e) {
        $failedCount++;
        echo "  [FAIL] {$data['slug']}: " . $e->getMessage() . "\n";
    }
}

echo "\n=== Summary ===\n";
echo "Updated: {$updatedCount}\n";
echo "Failed: {$failedCount}\n";

// Verify
echo "\n=== Verification ===\n";
$verify = $db->query("SELECT id, slug, title, LENGTH(history) as h_len, LENGTH(significance) as s_len, LENGTH(benefits) as b_len FROM donation_causes WHERE category = 'ekadashi' AND is_active = 1 ORDER BY id");
foreach ($verify->fetchAll() as $row) {
    $allOk = $row['h_len'] > 0 && $row['s_len'] > 0 && $row['b_len'] > 0;
    echo "  " . ($allOk ? '[OK]' : '[!!]') . " {$row['slug']}: hist={$row['h_len']} sig={$row['s_len']} ben={$row['b_len']}\n";
}

echo "\n=== Done! ===\n";
